/**
 * Emit the language-neutral conformance fixtures (issue #32) to `conformance/fixtures/`:
 *
 *   - one binary `<name>.azp` per {@link conformanceFixtures} entry;
 *   - `expectations.json` — for each fixture, the reference `verifyAzp` result (ok, signed, errors),
 *     the derived `signatureValid`, and the `verifyTrust` result against {@link TRUST_STORE};
 *   - `trust-keys.json` — the fixed author/registry public keys (+ their seeds) and the trust store;
 *   - `README.md` — a short pointer, regenerated so it can't drift.
 *
 * These are EMITTED artifacts of `@azphalt/conformance`, not hand-written: a host in any language
 * asserts against the committed `.azp` bytes + `expectations.json` without a JS toolchain, and the
 * `conformance-fixtures` CI job re-runs this and fails on any diff. That guarantee only holds because
 * every fixture is deterministic (fixed signing keys + EPOCH/zeroed archive timestamps).
 *
 * Run: `pnpm --filter @azphalt/conformance emit` (after a build), or `pnpm fixtures` from the root.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { AUTHOR_KEY, REGISTRY_KEY, TRUST_STORE, conformanceFixtures, evaluateFixture } from "./fixtures.js";

/** Walk up from this module to the workspace root (the dir with `pnpm-workspace.yaml`). */
function repoRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 10; i++) {
    if (existsSync(join(dir, "pnpm-workspace.yaml"))) return dir;
    const up = dirname(dir);
    if (up === dir) break;
    dir = up;
  }
  throw new Error("emit-fixtures: could not locate the workspace root (pnpm-workspace.yaml)");
}

function main(): void {
  const outDir = join(repoRoot(), "conformance", "fixtures");
  mkdirSync(outDir, { recursive: true });

  const fixtures = conformanceFixtures();
  const perFixture: Record<string, unknown> = {};

  for (const fx of fixtures) {
    const file = `${fx.name}.azp`;
    writeFileSync(join(outDir, file), fx.bytes);
    perFixture[file] = { description: fx.description, ...evaluateFixture(fx.bytes) };
  }

  const expectations = {
    formatVersion: "0.1",
    generator: "@azphalt/conformance emit-fixtures",
    description:
      "Expected verify + trust outcomes for each conformance fixture. Given the same .azp bytes " +
      "and trust-keys.json, a conforming host MUST reproduce the SEMANTIC results: verify.ok, " +
      "verify.signed, signatureValid, trust.trusted (and, when trusted, viaRegistryPublicKey). The " +
      "`errors` / `reason` strings are the JS reference's diagnostics — hosts in other languages will " +
      "word them differently and MAY reject at a different (earlier) stage, so match on the booleans, " +
      "not on error text. Regenerated by `pnpm --filter @azphalt/conformance emit`; the " +
      "conformance-fixtures CI job fails on any diff.",
    trustStore: TRUST_STORE,
    fixtures: perFixture,
  };
  writeJson(join(outDir, "expectations.json"), expectations);

  const trustKeys = {
    description:
      "Fixed, DETERMINISTIC test keys for the conformance fixtures — derived from constant 32-byte " +
      "seeds (seedHex). NEVER use these for real signing. `trustStore` is exactly what a host loads " +
      "to reproduce expectations.json: it trusts the registry key only, so signed-valid is untrusted " +
      "(author not in store) while countersigned-1hop is trusted transitively via the registry.",
    author: { keyId: AUTHOR_KEY.keyId, publicKey: AUTHOR_KEY.publicKey, seedHex: AUTHOR_KEY.seedHex },
    registry: { keyId: REGISTRY_KEY.keyId, publicKey: REGISTRY_KEY.publicKey, seedHex: REGISTRY_KEY.seedHex },
    trustStore: TRUST_STORE,
  };
  writeJson(join(outDir, "trust-keys.json"), trustKeys);

  writeFileSync(join(outDir, "README.md"), readme(fixtures.map((f) => f.name)));

  // eslint-disable-next-line no-console
  console.log(`emitted ${fixtures.length} fixtures + expectations.json + trust-keys.json → ${outDir}`);
}

function writeJson(path: string, value: unknown): void {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function readme(names: string[]): string {
  return `# azphalt conformance fixtures

**Generated — do not edit by hand.** Produced by \`@azphalt/conformance\` (\`src/emit-fixtures.ts\`);
regenerate with \`pnpm fixtures\` (root) or \`pnpm --filter @azphalt/conformance emit\`. The
\`conformance-fixtures\` CI job re-runs the generator and fails on any diff, so these bytes stay honest.

## What this is

A language-neutral set of binary \`.azp\` fixtures plus the expected \`verifyAzp\` / \`verifyTrust\`
outcomes, so a host in **any** language (Kotlin, Swift, Rust, …) can assert byte-for-byte conformance
with the \`@azphalt/azp\` reference — no JavaScript toolchain required. See azphalt issue #32.

## Files

- \`*.azp\` — the fixtures:
${names.map((n) => `  - \`${n}.azp\``).join("\n")}
- \`expectations.json\` — per fixture: the reference \`verify\` result (\`ok\`, \`signed\`, \`errors\`), the
  derived \`signatureValid\`, and the \`trust\` result (\`trusted\`, \`reason\`, …) against \`trustStore\`.
- \`trust-keys.json\` — the fixed author/registry public keys (with their constant seeds) and the
  \`trustStore\` a host loads to reproduce \`expectations.json\`.

## Determinism

Every fixture is reproducible: signing uses fixed Ed25519 keys derived from constant seeds (never
random keys), and archives ride \`@azphalt/azp\`'s \`EPOCH\` timestamp (or a zeroed STORED-zip). Identical
inputs ⇒ identical bytes in every environment — which is what lets CI diff-check them.

## How a non-JS host uses these

1. Load \`trust-keys.json\` → build a trust store from \`trustStore.keys[].publicKey\`.
2. For each \`*.azp\`, run your own verify + trust.
3. Assert your result matches the **semantic** fields of \`expectations.json[<file>]\`:
   \`verify.ok\`, \`verify.signed\`, \`signatureValid\`, and \`trust.trusted\` (plus \`viaRegistryPublicKey\`
   when trusted).

The \`errors\` and \`reason\` **strings are the JS reference's diagnostics** — a host in another language
will phrase them differently, and may reject a bad package at a different (earlier) stage. Match on the
booleans, not on the error text.

Note on \`duplicate-entry.azp\`: it packs two ZIP entries with the same name but different content — a
ZIP-confusion vector. Every conforming host must reject it (\`verify.ok === false\`). The reference keeps
the last copy and reports a digest mismatch; a hardened host that rejects on the duplicate name itself
is equally conforming. A host that silently keeps the *first* copy and accepts the package is **not**.
`;
}

main();
