import { example, remoteChecksum, type Example } from "../shared.js";

/**
 * `models` — AI model assets shipped as remote-header `.azp`s. Model files are large (MB–GB), so
 * none of these ship inline: each asset sets `path: ""` and points at a `remoteUrl` the host fetches,
 * with a `checksum` and `byteSize` for verification and download progress. The `role` is the load-
 * bearing field — it routes an otherwise-generic model graph (tflite/litert/onnx/sherpa) to the right
 * host pipeline (`"depth"`, `"segmentation"`, `"detection"`, `"asr"`, …). Payload is empty throughout.
 */
export const models: Example[] = [
  example({
    slug: "tflite-pose",
    summary: "A single-person 2D pose detector (.tflite, remote header).",
    manifest: {
      azphalt: "0.1",
      id: "com.azphalt.example.tflite-pose",
      name: "MoveNet Pose (TFLite)",
      version: "1.0.0",
      kind: "asset",
      license: "MIT",
      compat: ">=0.1",
      description: "A lightweight TFLite pose model emitting 17 body keypoints per frame.",
      author: "azphalt examples",
      capabilities: ["assets"],
      assets: [
        {
          type: "tflite",
          path: "",
          remoteUrl: "https://models.azphalt.dev/pose/movenet-singlepose-lightning-fp16.tflite",
          checksum: remoteChecksum("tflite-pose"),
          byteSize: 3_115_008,
          role: "pose",
          tags: ["pose", "keypoints", "mobile"],
          params: { inputSize: 192, keypoints: 17, format: "tflite" },
        },
      ],
    },
  }),
  example({
    slug: "tflite-segment",
    summary: "A real-time selfie / person segmentation mask (.tflite, remote header).",
    manifest: {
      azphalt: "0.1",
      id: "com.azphalt.example.tflite-segment",
      name: "Selfie Segmenter (TFLite)",
      version: "1.0.0",
      kind: "asset",
      license: "MIT",
      compat: ">=0.1",
      description: "A TFLite model producing a per-pixel foreground/background matte for backdrop swaps.",
      author: "azphalt examples",
      capabilities: ["assets"],
      assets: [
        {
          type: "tflite",
          path: "",
          remoteUrl: "https://models.azphalt.dev/segmentation/selfie-segmenter-256.tflite",
          checksum: remoteChecksum("tflite-segment"),
          byteSize: 2_764_800,
          role: "segmentation",
          tags: ["segmentation", "selfie", "matting"],
          params: { inputSize: 256, classes: 2, output: "alpha-mask", format: "tflite" },
        },
      ],
    },
  }),
  example({
    slug: "litert-depth",
    summary: "Monocular depth estimation from a single image (.litert, remote header).",
    manifest: {
      azphalt: "0.1",
      id: "com.azphalt.example.litert-depth",
      name: "MiDaS Depth (LiteRT)",
      version: "1.0.0",
      kind: "asset",
      license: "MIT",
      compat: ">=0.1",
      description: "A LiteRT depth model that predicts an inverse-depth map from one RGB frame.",
      author: "azphalt examples",
      capabilities: ["assets"],
      assets: [
        {
          type: "litert",
          path: "",
          remoteUrl: "https://models.azphalt.dev/depth/midas-v21-small-256.litert",
          checksum: remoteChecksum("litert-depth"),
          byteSize: 16_965_632,
          role: "depth",
          tags: ["depth", "monocular", "midas"],
          params: { inputSize: 256, output: "inverse-depth", format: "litert" },
        },
      ],
    },
  }),
  example({
    slug: "litert-upscale",
    summary: "A 4x single-image super-resolution model (.litert, remote header).",
    manifest: {
      azphalt: "0.1",
      id: "com.azphalt.example.litert-upscale",
      name: "Real-ESRGAN x4 (LiteRT)",
      version: "1.0.0",
      kind: "asset",
      license: "MIT",
      compat: ">=0.1",
      description: "A LiteRT super-resolution model that upscales tiles by 4x with detail recovery.",
      author: "azphalt examples",
      capabilities: ["assets"],
      assets: [
        {
          type: "litert",
          path: "",
          remoteUrl: "https://models.azphalt.dev/upscale/real-esrgan-x4plus.litert",
          checksum: remoteChecksum("litert-upscale"),
          byteSize: 67_633_152,
          role: "upscale",
          tags: ["super-resolution", "upscale", "esrgan"],
          params: { scale: 4, tileSize: 128, format: "litert" },
        },
      ],
    },
  }),
  example({
    slug: "onnx-detect",
    summary: "A COCO object detector over 80 classes (.onnx, remote header).",
    manifest: {
      azphalt: "0.1",
      id: "com.azphalt.example.onnx-detect",
      name: "YOLOv8n Detector (ONNX)",
      version: "1.0.0",
      kind: "asset",
      license: "MIT",
      compat: ">=0.1",
      description: "An ONNX object-detection graph returning boxes and labels for 80 COCO classes.",
      author: "azphalt examples",
      capabilities: ["assets"],
      assets: [
        {
          type: "onnx",
          path: "",
          remoteUrl: "https://models.azphalt.dev/detection/yolov8n.onnx",
          checksum: remoteChecksum("onnx-detect"),
          byteSize: 13_107_200,
          role: "detection",
          tags: ["detection", "yolo", "coco"],
          params: { inputSize: 640, classes: 80, labels: "coco", format: "onnx" },
        },
      ],
    },
  }),
  example({
    slug: "onnx-embed",
    summary: "A 512-D face-recognition embedding model (.onnx, remote header).",
    manifest: {
      azphalt: "0.1",
      id: "com.azphalt.example.onnx-embed",
      name: "ArcFace Embedding (ONNX)",
      version: "1.0.0",
      kind: "asset",
      license: "MIT",
      compat: ">=0.1",
      description: "An ONNX model mapping an aligned face crop to a 512-dimension identity vector.",
      author: "azphalt examples",
      capabilities: ["assets"],
      assets: [
        {
          type: "onnx",
          path: "",
          remoteUrl: "https://models.azphalt.dev/embedding/arcface-r100.onnx",
          checksum: remoteChecksum("onnx-embed"),
          byteSize: 261_193_728,
          role: "embedding",
          tags: ["embedding", "face", "arcface"],
          params: { inputSize: 112, embeddingDim: 512, format: "onnx" },
        },
      ],
    },
  }),
  example({
    slug: "sherpa-asr-en",
    summary: "A streaming English speech-to-text bundle (sherpa, remote header).",
    manifest: {
      azphalt: "0.1",
      id: "com.azphalt.example.sherpa-asr-en",
      name: "Sherpa Zipformer ASR (English)",
      version: "1.0.0",
      kind: "asset",
      license: "MIT",
      compat: ">=0.1",
      description: "A sherpa-onnx streaming transducer bundle transcribing 16 kHz English audio.",
      author: "azphalt examples",
      capabilities: ["assets"],
      assets: [
        {
          type: "sherpa-bundle",
          path: "",
          remoteUrl: "https://models.azphalt.dev/asr/sherpa-onnx-streaming-zipformer-en-2023-06-26.tar.bz2",
          checksum: remoteChecksum("sherpa-asr-en"),
          byteSize: 314_572_800,
          role: "asr",
          tags: ["asr", "speech-to-text", "english"],
          params: { language: "en", modelType: "transducer", sampleRate: 16000, streaming: true, format: "sherpa-bundle" },
        },
      ],
    },
  }),
  example({
    slug: "sherpa-tts-en",
    summary: "An English neural text-to-speech voice bundle (sherpa, remote header).",
    manifest: {
      azphalt: "0.1",
      id: "com.azphalt.example.sherpa-tts-en",
      name: "Sherpa VITS TTS (English)",
      version: "1.0.0",
      kind: "asset",
      license: "MIT",
      compat: ">=0.1",
      description: "A sherpa-onnx VITS voice bundle synthesizing 22.05 kHz English speech from text.",
      author: "azphalt examples",
      capabilities: ["assets"],
      assets: [
        {
          type: "sherpa-bundle",
          path: "",
          remoteUrl: "https://models.azphalt.dev/tts/vits-piper-en_US-libritts-medium.tar.bz2",
          checksum: remoteChecksum("sherpa-tts-en"),
          byteSize: 78_643_200,
          role: "tts",
          tags: ["tts", "text-to-speech", "english"],
          params: { language: "en", voices: 904, sampleRate: 22050, format: "sherpa-bundle" },
        },
      ],
    },
  }),
];
